#!/bin/bash -e

make ${@} 2>&1 | perl -wln -M'Term::ANSIColor' -e '
m/error/i and print "\e[1;91m", "$_", "\e[0m"
or
m/warning/i and print "\e[1;93m", "$_", "\e[0m"
or
m/note/i and print "\e[1;92m", "$_", "\e[0m"
or
print; '
